[package]
name = "QwikTrade"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
egui_plot = "0.34.0"
flume = "0.11.1"
rand = "0.9.2"
reqwest = "0.12.24"
serde = "1.0.228"
serde_json = "1.0.145"
ta = "0.5.0"
tokio = "1.48.0"
tokio-tungstenite = "0.28.0"
